/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package programa3;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jzy3d.analysis.AnalysisLauncher;
import programa3.KNN;

/**
 *
 * @author jessi
 */
public class Interfaz extends javax.swing.JFrame  {
    boolean generado = true;
    int puntos, vecinos, clases, distancia,escala,x,y,z;
    KNN k;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        this.setLocationRelativeTo(null);
        initComponents();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        panelOpciones = new javax.swing.JPanel();
        labelNumeroClases = new javax.swing.JLabel();
        labelZ = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btbReiciar = new javax.swing.JButton();
        textZ = new javax.swing.JTextField();
        labelY = new javax.swing.JLabel();
        textY = new javax.swing.JTextField();
        labelX = new javax.swing.JLabel();
        textX = new javax.swing.JTextField();
        labelDistancia = new javax.swing.JLabel();
        boxDistancia = new javax.swing.JComboBox<>();
        textVecinos = new javax.swing.JTextField();
        textClases = new javax.swing.JTextField();
        textPuntos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        labeNumVecinos = new javax.swing.JLabel();
        labelNumPuntos = new javax.swing.JLabel();
        labelEscala = new javax.swing.JLabel();
        textEscala = new javax.swing.JTextField();
        labelClaficado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelColor = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelOpciones.setBackground(new java.awt.Color(204, 255, 204));

        labelNumeroClases.setText("Número de clases");

        labelZ.setText("Z");

        btnGraficar.setText("GRAFICAR");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btbReiciar.setText("REINICIAR");
        btbReiciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbReiciarActionPerformed(evt);
            }
        });

        textZ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textZKeyTyped(evt);
            }
        });

        labelY.setText("Y");

        textY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textYKeyReleased(evt);
            }
        });

        labelX.setText("X");

        textX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textXKeyTyped(evt);
            }
        });

        labelDistancia.setText("Distancia");

        boxDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euclidiana", "Semiverseno", "Manhattan", "Chebyshev" }));
        boxDistancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDistanciaActionPerformed(evt);
            }
        });

        textVecinos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textVecinosKeyTyped(evt);
            }
        });

        textClases.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textClasesKeyTyped(evt);
            }
        });

        textPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPuntosActionPerformed(evt);
            }
        });
        textPuntos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPuntosKeyTyped(evt);
            }
        });

        jLabel1.setText("Coordenadas");

        labeNumVecinos.setText("Número de vecinos ");

        labelNumPuntos.setText("Número de puntos");

        labelEscala.setText("Escala");

        textEscala.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textEscalaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panelColorLayout = new javax.swing.GroupLayout(panelColor);
        panelColor.setLayout(panelColorLayout);
        panelColorLayout.setHorizontalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );
        panelColorLayout.setVerticalGroup(
            panelColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addComponent(labelX)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addComponent(labelClaficado, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(panelColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelOpcionesLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btbReiciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalir))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOpcionesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnGraficar)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(labelY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelZ)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textZ, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textEscala))))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelOpcionesLayout.createSequentialGroup()
                                    .addComponent(labeNumVecinos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textVecinos, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOpcionesLayout.createSequentialGroup()
                                    .addComponent(labelNumPuntos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelOpcionesLayout.createSequentialGroup()
                                    .addComponent(labelNumeroClases)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textClases))
                                .addGroup(panelOpcionesLayout.createSequentialGroup()
                                    .addComponent(labelDistancia)
                                    .addGap(40, 40, 40)
                                    .addComponent(boxDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                                .addComponent(labelEscala)
                                .addGap(25, 25, 25)))))
                .addGap(18, 18, 18))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumPuntos)
                    .addComponent(textPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumeroClases))
                .addGap(18, 18, 18)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeNumVecinos)
                    .addComponent(textVecinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDistancia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelEscala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelX)
                    .addComponent(textX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelY)
                    .addComponent(textY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelZ)
                    .addComponent(textZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEscala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficar)
                .addGap(17, 17, 17)
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btbReiciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelClaficado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxDistanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDistanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDistanciaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        //Se conprueba que se han ingresado datos a los JtextField
        if(!"".equals(textPuntos.getText()) && Integer.parseInt(textPuntos.getText())!=0 &&!"".equals(textClases.getText()) && Integer.parseInt(textClases.getText())!=0 && !"".equals(textVecinos.getText()) && Integer.parseInt(textVecinos.getText())!=0 && !"".equals(textEscala.getText()) && Integer.parseInt(textEscala.getText())!=0 && !"".equals(textX.getText()) && !"".equals(textY.getText()) && !"".equals(textZ.getText())){
            puntos = Integer.parseInt(textPuntos.getText());
            distancia = boxDistancia.getSelectedIndex();
            vecinos = Integer.parseInt(textVecinos.getText());
            clases = Integer.parseInt(textClases.getText());
            escala = Integer.parseInt(textEscala.getText());
            x = Integer.parseInt(textX.getText());
            y = Integer.parseInt(textY.getText());
            z = Integer.parseInt(textZ.getText());
            //Se comprueba que los datos de las coordenadas esten dentro del plano
            if(x<=escala && x>=0 && y<=escala && y>=0 && z<=escala && z>=0){
                //Se compureba que los vecinos y clases son menores a la cantidad de puntos disponibles
                if(vecinos< puntos && clases<puntos){
                    //En la primera graficación se genera la grafica y se inicia la clasificación del punto ingresado
                    if(generado){
                       try{
                            k = new KNN(puntos,clases,vecinos,escala,labelClaficado,panelColor);
                            k.clasificarPunto(x, y, z,distancia);
                            AnalysisLauncher.open(k);
                            
                            generado = false;
                        }
                       catch(Exception e){}
                       //Se inabilita los jtextfield
                       textVecinos.setEnabled(false);
                       textClases.setEnabled(false);
                       textPuntos.setEnabled(false);
                       textEscala.setEnabled(false);
                    }
                    else{
                    //Para las siguientes graficas, unicamente sera necesario graficar el punto ingresado 
                        k.clasificarPunto(x, y, z,distancia);
                }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Error: Vecinos o clases mayor a la cantidad de puntos");
                }
            }
            else{{
                JOptionPane.showMessageDialog(null, "Error: Las coordenadas no se encuentran dentro de la escala");   
            }}
        }
        else{
            JOptionPane.showMessageDialog(null, "Error: Los datos no se han completado correctamente");
        
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void textPuntosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPuntosKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }
    }//GEN-LAST:event_textPuntosKeyTyped

    private void textClasesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textClasesKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_textClasesKeyTyped

    private void textVecinosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textVecinosKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_textVecinosKeyTyped

    private void textXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textXKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_textXKeyTyped

    private void textYKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textYKeyReleased
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_textYKeyReleased

    private void textZKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textZKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_textZKeyTyped

    private void textEscalaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textEscalaKeyTyped
        //Se devuelve lo que esta escrito en el cuadro de texto
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        //Se verifica que no se ingresen letras
        if (!numeros)
            {
                evt.consume();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_textEscalaKeyTyped

    private void btbReiciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbReiciarActionPerformed
        textVecinos.setEnabled(true);
        textClases.setEnabled(true);
        textPuntos.setEnabled(true);
        textEscala.setEnabled(true);
        textVecinos.setText("");
        textClases.setText("");
        textPuntos.setText("");
        textEscala.setText("");
        textX.setText("");
        textY.setText("");
        textZ.setText("");
        labelClaficado.setText("");
        generado = true;
        panelColor.setBackground(Color.WHITE);


        // TODO add your handling code here:
    }//GEN-LAST:event_btbReiciarActionPerformed

    private void textPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPuntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDistancia;
    private javax.swing.JButton btbReiciar;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labeNumVecinos;
    private javax.swing.JLabel labelClaficado;
    private javax.swing.JLabel labelDistancia;
    private javax.swing.JLabel labelEscala;
    private javax.swing.JLabel labelNumPuntos;
    private javax.swing.JLabel labelNumeroClases;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JLabel labelZ;
    private javax.swing.JPanel panelColor;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JTextField textClases;
    private javax.swing.JTextField textEscala;
    private javax.swing.JTextField textPuntos;
    private javax.swing.JTextField textVecinos;
    private javax.swing.JTextField textX;
    private javax.swing.JTextField textY;
    private javax.swing.JTextField textZ;
    // End of variables declaration//GEN-END:variables
}
